### ISSUE TITLE
file system permissions are broken

### ISSUE THREAD

**Issue by MrTango** [plone/ansible.plone_server#82]
In the current master and also in the tag 1.2.8 the file system permissions are broken:

```
root@plone-test1-deb8-32bit:/usr/local/plone-4.3/example# su plone_daemon 
$ pwd
/usr/local/plone-4.3/example
$ ./bin/client_reserved run scripts/addPloneSite.py  
Traceback (most recent call last):
  File "/usr/local/plone-4.3/example/parts/client_reserved/bin/interpreter", line 260, in <module>
    exec(_val)
  File "<string>", line 1, in <module>
  File "/usr/local/plone-4.3/buildout-cache/eggs/Zope2-2.13.23-py2.7.egg/Zope2/__init__.py", line 51, in app
    startup()
  File "/usr/local/plone-4.3/buildout-cache/eggs/Zope2-2.13.23-py2.7.egg/Zope2/__init__.py", line 47, in startup
    _startup()
  File "/usr/local/plone-4.3/buildout-cache/eggs/Zope2-2.13.23-py2.7.egg/Zope2/App/startup.py", line 81, in startup
    DB = dbtab.getDatabase('/', is_root=1)
  File "/usr/local/plone-4.3/buildout-cache/eggs/Zope2-2.13.23-py2.7.egg/Zope2/Startup/datatypes.py", line 287, in getDatabase
    db = factory.open(name, self.databases)
  File "/usr/local/plone-4.3/buildout-cache/eggs/Zope2-2.13.23-py2.7.egg/Zope2/Startup/datatypes.py", line 185, in open
    DB = self.createDB(database_name, databases)
  File "/usr/local/plone-4.3/buildout-cache/eggs/Zope2-2.13.23-py2.7.egg/Zope2/Startup/datatypes.py", line 182, in createDB
    return ZODBDatabase.open(self, databases)
  File "/usr/local/plone-4.3/buildout-cache/eggs/ZODB3-3.10.5-py2.7-linux-i686.egg/ZODB/config.py", line 101, in open
    storage = section.storage.open()
  File "/usr/local/plone-4.3/buildout-cache/eggs/ZODB3-3.10.5-py2.7-linux-i686.egg/ZODB/config.py", line 220, in open
    **options)
  File "/usr/local/plone-4.3/buildout-cache/eggs/ZODB3-3.10.5-py2.7-linux-i686.egg/ZEO/ClientStorage.py", line 387, in __init__
    self.fshelper = ZODB.blob.FilesystemHelper(blob_dir)
  File "/usr/local/plone-4.3/buildout-cache/eggs/ZODB3-3.10.5-py2.7-linux-i686.egg/ZODB/blob.py", line 330, in __init__
    layout_name = auto_layout_select(base_dir)
  File "/usr/local/plone-4.3/buildout-cache/eggs/ZODB3-3.10.5-py2.7-linux-i686.egg/ZODB/blob.py", line 516, in auto_layout_select
    for name in os.listdir(path):
OSError: [Errno 13] Permission denied: '/var/local/plone-4.3/example/blobstorage'
```

tag 1.2.5 works with the same playbook.
OS: Debian 32bit on DiagitalOcean

**Comment by smcmahon** [comment]
I need some help with this one: I'm unable to reproduce the problem.

I've run tests with both Trusty and Jessie, and in both cases blobstorage ends up owned by plone_daemon and there's no problem with the step that adds the Plone site.

Any clues as to what's going on? Interim steps?

**Comment by MrTango** [comment]
ok, I'll try again with some different scenarios to find out in which cases that happen.

**Comment by MrTango** [comment]
if you let run this playbook on DigitalOcean (Debian8 32bit) with the master of ansible.plone_server it should give you the error below.
```
$ cat playbook.yml 
---
# vim:ft=ansible:

- hosts: all
  become: yes
  gather_facts: yes

  pre_tasks:
    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=3600

    - name: Ensure required packages
      apt: pkg={{ item }} state=present
      with_items:
        - nginx
        - vim-nox
        - git
        - openssl
        - sudo
        - build-essential
        - python-dev
        - python-virtualenv
        - python-pip
        - libz-dev
        - libssl-dev
        - libjpeg-dev
        - libxslt1-dev
        - libjpeg-dev
        - libopenjpeg-dev
        - libfreetype6-dev
        - libwebp-dev
        - poppler-utils
        - wv
        - lynx-cur
        - unzip
        - supervisor

    - name: Update host
      apt: upgrade=dist update_cache=yes

    - name: Add ansible user
      user: name=ansible shell=/bin/bash groups=sudo append=yes

  roles:

    - role: jdauphant.nginx
      tags: nginx
      nginx_http_params:
        - sendfile "on"
        - client_max_body_size "50m"
        - access_log "/var/log/nginx/access.log" 
      nginx_sites:
        client1:
          - listen 80
          - location / { proxy_pass http://127.0.0.1:8081/VirtualHostBase/http/test.derico.de:80/Plone/VirtualHostRoot/; }

    - role: ansible.plone_server
      plone_instance_name: plone01
      plone_site_id: Plone
      plone_default_language: de
      plone_major_version: '4.3'
      plone_version: '4.3.9'
      plone_initial_password: admin

      plone_zserver_threads: 2
      plone_additional_eggs:
        - plone.app.mosaic
        - plone.app.widgets
      plone_zcml_slugs:
        - quintagroup.portlet.pfg
      plone_additional_versions:
        - "Products.PloneFormGen = 1.7.19"
        - "Products.EasyNewsletter = 2.6.15"
        - "plone.tiles = 1.5.2"
        - "plone.app.tiles = 2.2.1"
        - "plone.app.standardtiles = 1.0"
        - "plone.app.blocks = 3.1.0"
        - "plone.app.drafts = 1.0"
        - "plone.app.widgets = 1.8.0"
      plone_sources:
```

The error:
```
cmd: bin/client_reserved run scripts/addPloneSite.py

start: 2016-05-30 04:32:51.757217

end: 2016-05-30 04:33:06.598990

delta: 0:00:14.841773

stderr: Traceback (most recent call last):
  File "/usr/local/plone-4.3/plone01/parts/client_reserved/bin/interpreter", line 270, in <module>
    exec(_val)
  File "<string>", line 1, in <module>
  File "/usr/local/plone-4.3/buildout-cache/eggs/Zope2-2.13.24-py2.7.egg/Zope2/__init__.py", line 51, in app
    startup()
  File "/usr/local/plone-4.3/buildout-cache/eggs/Zope2-2.13.24-py2.7.egg/Zope2/__init__.py", line 47, in startup
    _startup()
  File "/usr/local/plone-4.3/buildout-cache/eggs/Zope2-2.13.24-py2.7.egg/Zope2/App/startup.py", line 81, in startup
    DB = dbtab.getDatabase('/', is_root=1)
  File "/usr/local/plone-4.3/buildout-cache/eggs/Zope2-2.13.24-py2.7.egg/Zope2/Startup/datatypes.py", line 287, in getDatabase
    db = factory.open(name, self.databases)
  File "/usr/local/plone-4.3/buildout-cache/eggs/Zope2-2.13.24-py2.7.egg/Zope2/Startup/datatypes.py", line 185, in open
    DB = self.createDB(database_name, databases)
  File "/usr/local/plone-4.3/buildout-cache/eggs/Zope2-2.13.24-py2.7.egg/Zope2/Startup/datatypes.py", line 182, in createDB
    return ZODBDatabase.open(self, databases)
  File "/usr/local/plone-4.3/buildout-cache/eggs/ZODB3-3.10.5-py2.7-linux-i686.egg/ZODB/config.py", line 101, in open
    storage = section.storage.open()
  File "/usr/local/plone-4.3/buildout-cache/eggs/ZODB3-3.10.5-py2.7-linux-i686.egg/ZODB/config.py", line 220, in open
    **options)
  File "/usr/local/plone-4.3/buildout-cache/eggs/ZODB3-3.10.5-py2.7-linux-i686.egg/ZEO/ClientStorage.py", line 387, in __init__
    self.fshelper = ZODB.blob.FilesystemHelper(blob_dir)
  File "/usr/local/plone-4.3/buildout-cache/eggs/ZODB3-3.10.5-py2.7-linux-i686.egg/ZODB/blob.py", line 330, in __init__
    layout_name = auto_layout_select(base_dir)
  File "/usr/local/plone-4.3/buildout-cache/eggs/ZODB3-3.10.5-py2.7-linux-i686.egg/ZODB/blob.py", line 516, in auto_layout_select
    for name in os.listdir(path):
OSError: [Errno 13] Permission denied: '/var/local/plone-4.3/plone01/blobstorage'

NO MORE HOSTS LEFT *************************************************************
	to retry, use: --limit @playbook.retry
```

The persion settings in this path are:
```
root@debian-512mb-fra1-01:~# ls -la  /var/local/plone-4.3/plone01/blobstorage
total 8
drwx--S--- 2 plone_buildout plone_group 4096 May 30 04:23 .
drwxrws--- 9 plone_daemon   plone_group 4096 May 30 04:28 ..
root@debian-512mb-fra1-01:~# ls -la  /var/local/plone-4.3/plone01/
total 36
drwxrws--- 9 plone_daemon   plone_group 4096 May 30 04:28 .
drwxr-xr-x 4 root           staff       4096 May 30 04:22 ..
drwx--S--- 2 plone_buildout plone_group 4096 May 30 04:23 blobstorage
drwxr-sr-x 3 plone_buildout plone_group 4096 May 30 04:23 client1
drwxr-sr-x 3 plone_buildout plone_group 4096 May 30 04:28 client2
drwxr-sr-x 3 plone_buildout plone_group 4096 May 30 04:28 client_reserved
drwxr-sr-x 2 plone_buildout plone_group 4096 May 30 04:23 filestorage
drwx------ 2 plone_daemon   plone_group 4096 May 30 04:22 .python-eggs
drwxr-sr-x 2 plone_buildout plone_group 4096 May 30 04:23 zeoserver
```

**Comment by MrTango** [comment]
I've testen with tag 1.2.6 also and this has the same Problem. Only tag 1.2.5 works.

**Comment by smcmahon** [comment]
Thanks! I'll tackle this as soon as I'm back from PyCon US.

**Comment by smcmahon** [comment]
OK, this is frustrating. I wasn't able to reproduce the problem. I tried with Jessie 8.3 64 via Vagrant and a brand-new 8.3 32-bit on digital ocean. The playbook ran with no problems. (ansible-playbook 2.1.0.0)

Anything done to the server environment before running the playbook?

**Comment by MrTango** [comment]
No, I created a new droplet debian 8 32bit, location Frankfurt and ran the playbook above. ansible-playbook 2.0.2.0 but I'll try the version 2.1.0.0. soon.

**Comment by MrTango** [comment]
Hm, interesting, it works with ansible-2.1.0.0 but not with 2.0.2.0 which comes with Debian ;)

**Comment by smcmahon** [comment]
That is *very* interesting.

**Comment by djowett** [comment]
I'm seeing similar on Plone 4.3.7 / Ubuntu 14.04

If I try backup with plone_daemon I get:

    $ sudo -u plone_daemon bin/zipbackup
    INFO: Please wait while backing up database file: /var/local/plone-4.3/demo/filestorage/Data.fs to /usr/local/plone-4.3/demo/var/zipbackups
    No handlers could be found for logger "ZODB.FileStorage"
    Traceback (most recent call last):
      File "/usr/local/plone-4.3/demo/bin/repozo", line 23, in <module>
        sys.exit(ZODB.scripts.repozo.main())
      File "/usr/local/plone-4.3/buildout-cache/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/scripts/repozo.py", line 611, in main
        do_backup(options)
      File "/usr/local/plone-4.3/buildout-cache/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/scripts/repozo.py", line 500, in do_backup
        do_full_backup(options)
      File "/usr/local/plone-4.3/buildout-cache/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/scripts/repozo.py", line 447, in do_full_backup
        fs._index.save(pos, index_file)
      File "/usr/local/plone-4.3/buildout-cache/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/fsIndex.py", line 99, in save
        with open(fname, 'wb') as f:
    IOError: [Errno 13] Permission denied: '/usr/local/plone-4.3/demo/var/zipbackups/2016-06-16-18-42-43.index'
    ERROR: Repozo command failed. See message above.
    ERROR: Halting execution due to error; not backing up blobs.


If I try it with plone_buildout I get:

    $ sudo -u plone_buildout bin/zipbackup
    INFO: Please wait while backing up database file: /var/local/plone-4.3/demo/filestorage/Data.fs to /usr/local/plone-4.3/demo/var/zipbackups
    No handlers could be found for logger "ZODB.FileStorage"
    INFO: Removed 4 file(s) belonging to old backups, the latest 1 full backups have been kept.
    INFO: Please wait while backing up blobs from /var/local/plone-4.3/demo/blobstorage to /usr/local/plone-4.3/demo/var/blobstoragezips
    INFO: Renaming blobstorage.0.tar.gz to blobstorage.1.tar.gz.
    INFO: tar czf /usr/local/plone-4.3/demo/var/blobstoragezips/blobstorage.0.tar.gz -C /var/local/plone-4.3/demo/blobstorage .
    tar: /var/local/plone-4.3/demo/blobstorage: Cannot open: Permission denied
    tar: Error is not recoverable: exiting now

I guess it's plone_buildout mean't to be running backups?

**Comment by djowett** [comment]
Ok, I'm mistaken it's meant to be plone_daemon.

My permissions were:

    $ ls -al /var/local/plone-4.3/demo/
    total 32
    drwxrws--- 8 plone_daemon   plone_group 4096 Jun 16 13:55 .
    drwxr-xr-x 4 root           staff       4096 Jun 14 14:08 ..
    drwx--S--- 3 plone_daemon   plone_group 4096 Jun 16 13:55 blobstorage
    drwxrws--- 3 plone_buildout plone_group 4096 Jun 17 06:39 client1
    drwxrws--- 3 plone_buildout plone_group 4096 Jun 16 13:54 client_reserved
    drwxrws--- 2 plone_buildout plone_group 4096 Jun 16 13:55 filestorage
    drwx------ 2 plone_daemon   plone_group 4096 Jun 14 14:08 .python-eggs
    drwxrws--- 2 plone_buildout plone_group 4096 Jun 16 13:55 zeoserver

I note my blobstorage is owned by plone_daemon rather than plone_buildout, but I figured that the main issue was the missing group permissions.  I fixed it manually with `chmod -R 2770  /var/local/plone-4.3/highfields_demo/blobstorage/`.  I don't know what sets the permissions & ownership of blobstorage, but it doesn't seem to me to be the Ansible playbook or role, so perhaps the problem & solution are elsewhere in Plone?

**Comment by smcmahon** [comment]
The var directory can have files created by buildout *or* by the ZEO server and client processes. That's why we've got the plone_group and the unusual setgid bits. The blobstorage directory itself is created by the zeoserver daemon.

**Comment by djowett** [comment]
So is 2770 the correct permissions for thé blobstorage directory ?



---- Steve McMahon wrote ----

**Comment by smcmahon** [comment]
"Correct" is any ownership/permissions that allows the daemon to write to the directory.

**Comment by smcmahon** [comment]
Closing this for now. Re-open if we get any more information that might help diagnose or fix for old Ansible.

**Comment by djowett** [comment]
Can I just note that lines in the setpermission part are swallowing errors

https://github.com/plone/ansible.plone_server/blob/master/templates/buildout.cfg.j2#L207

Trying to execute them manually gave me errors on setting the permissions.

**Comment by MrTango** [comment]
Still the same issue but on Ubuntu:

Groups are correct:
```
$ groups plone_buildout 
plone_buildout : plone_group
```
and 
```
$ groups plone_daemon
plone_daemon : plone_group
```

permissions are set as follow:

```
ls -la /var/local/plone-5.0/
total 12
drwxr-xr-x 3 root         staff       4096 Dec  5 13:32 .
drwxrwsr-x 3 root         staff       4096 Dec  5 13:31 ..
drwxrws--- 8 plone_daemon plone_group 4096 Dec  5 13:39 my-plone

ls -la /var/local/plone-5.0/my-plone/
total 32
drwxrws--- 8 plone_daemon   plone_group 4096 Dec  5 13:39 .
drwxr-xr-x 3 root           staff       4096 Dec  5 13:32 ..
drwx--S--- 2 plone_buildout plone_group 4096 Dec  5 13:34 blobstorage
drwxr-sr-x 3 plone_buildout plone_group 4096 Dec  5 13:34 client1
drwxr-sr-x 3 plone_buildout plone_group 4096 Dec  5 13:39 client_reserved
drwxr-sr-x 2 plone_buildout plone_group 4096 Dec  5 13:34 filestorage
drwx------ 2 plone_daemon   plone_group 4096 Dec  5 13:32 .python-eggs
drwxr-sr-x 2 plone_buildout plone_group 4096 Dec  5 13:34 zeoserver

```


I still get this error when running buildout:

```
cmd: bin/client_reserved run scripts/addPloneSite.py

start: 2016-12-05 13:40:25.958890

end: 2016-12-05 13:40:29.959216

delta: 0:00:04.000326

stderr: Traceback (most recent call last):
  File "/usr/local/plone-5.0/my-plone/parts/client_reserved/bin/interpreter", line 278, in <module>
    exec(_val)
  File "<string>", line 1, in <module>
  File "/usr/local/plone-5.0/buildout-cache/eggs/Zope2-2.13.23-py2.7.egg/Zope2/__init__.py", line 51, in app
    startup()
  File "/usr/local/plone-5.0/buildout-cache/eggs/Zope2-2.13.23-py2.7.egg/Zope2/__init__.py", line 47, in startup
    _startup()
  File "/usr/local/plone-5.0/buildout-cache/eggs/Zope2-2.13.23-py2.7.egg/Zope2/App/startup.py", line 81, in startup
    DB = dbtab.getDatabase('/', is_root=1)
  File "/usr/local/plone-5.0/buildout-cache/eggs/Zope2-2.13.23-py2.7.egg/Zope2/Startup/datatypes.py", line 287, in getDatabase
    db = factory.open(name, self.databases)
  File "/usr/local/plone-5.0/buildout-cache/eggs/Zope2-2.13.23-py2.7.egg/Zope2/Startup/datatypes.py", line 185, in open
    DB = self.createDB(database_name, databases)
  File "/usr/local/plone-5.0/buildout-cache/eggs/Zope2-2.13.23-py2.7.egg/Zope2/Startup/datatypes.py", line 182, in createDB
    return ZODBDatabase.open(self, databases)
  File "/usr/local/plone-5.0/buildout-cache/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/config.py", line 101, in open
    storage = section.storage.open()
  File "/usr/local/plone-5.0/buildout-cache/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/config.py", line 220, in open
    **options)
  File "/usr/local/plone-5.0/buildout-cache/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZEO/ClientStorage.py", line 387, in __init__
    self.fshelper = ZODB.blob.FilesystemHelper(blob_dir)
  File "/usr/local/plone-5.0/buildout-cache/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/blob.py", line 330, in __init__
    layout_name = auto_layout_select(base_dir)
  File "/usr/local/plone-5.0/buildout-cache/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/blob.py", line 516, in auto_layout_select
    for name in os.listdir(path):
OSError: [Errno 13] Permission denied: '/var/local/plone-5.0/my-plone/blobstorage'
	
```

**Comment by MrTango** [comment]
I think the folder permissions are not correct here.
A folder should be always executeable, but it isn't here for the group "plone_group".

`drwxr-sr-x 2 plone_buildout plone_group 4096 Dec  5 13:34 zeoserver`

Thats why also the zeoserver is not starting.
And the blobstorage folder doesn't have the write permissions for the plone_group.

`drwx--S--- 2 plone_buildout plone_group 4096 Dec  5 13:34 blobstorage`

After setting the rights

**Comment by smcmahon** [comment]
On it!

**Comment by smcmahon** [comment]
MrTango, what's the umask on your target system, particularly for root? If it's not 022 (or 002), that could explain some of this.

**Comment by MrTango** [comment]
it's 

```
root@plone-m-test:~# umask
0022
```

**Comment by MrTango** [comment]
I just noticed that had used the plone_buildout_git_repo option in this case.
I'll test with out also. But i noticed that you set permissions in your buildout config, maybe it's better to handle this in ansible, so that a buildout configuration works easier together with ansible.
I'll back with more infos soon.

**Comment by djowett** [comment]
I came back to this, so another 2c worth:

This might come down to subtle differences between versions of Plone, or plone.recipe.zope2instance or something else. Changes like [this](https://github.com/plone/plone.recipe.zope2instance/commit/6dd0650ab3de6f667802e4e630cd2a5ea594f6fe) could change the effective umask.

Might be stating the obvious, but if `blobstorage` directory isn't owned by plone_buildout then the chmod command in buildout will fail silently.

Right back to something else

**Comment by djowett** [comment]
http://unix.stackexchange.com/a/229553 might be useful

**Comment by ramiroluz** [comment]
It happening with me. 

I am using plone_buildout_git_repo. The first error, found in supervisor log, 
IOError: [Errno 13] Permission denied: '/usr/local/plone-4.3/Plone/eggs/Products.SQLAlchemyDA-0.5.1-py2.7.egg/EGG-INFO/namespace_packages.txt'

Fixed the permission of the file (namespace_packages.txt) with chmod, got a similar error:
IOError: [Errno 13] Permission denied: '/usr/local/plone-4.3/Plone/var/filestorage/Data.fs.lock'"

Fixed the permission of the folder (filestorage), got:
OSError: [Errno 13] Permission denied: '/usr/local/plone-4.3/Plone/var/blobstorage'

Fixed the permission of the folder (blobstorage), then it worked.

To reproduce:
$ git clone git@github.com:plone/ansible-playbook.git
$ git checkout -b STABLE
$ ansible-galaxy -p roles -r requirements.yml install

Create a local-configure.yml like this:
admin_email: admin@example.com
plone_initial_password: "SOMEPASS"
install_muninnode: no
additional_packages:
    - sudo
    - libsasl2-dev
    - libldap2-dev
plone_major_version: '4.3'
plone_version: '4.3.14'
# 4 clients
plone_client_count: 4
# smallish
plone_zodb_cache_size: 15000
# and enforce that with a memory-monitor
plone_client_max_memory: 750MB
plone_instance_name: Plone
plone_buildout_git_repo: https://github.com/CMCuritiba/portalmodelo.git
plone_buildout_git_version: master
plone_default_language: pt-BR

Then run:
vagrant up

**Comment by djowett** [comment]
Hi @fulv,
   for the record 9b00c3e was me, but it was committed after this issue was raised, not before. 
It does of course not send errors to `/dev/null` as was happening before (see [my comment above](#issuecomment-238635348))

**Comment by djowett** [comment]
I'm beginning to think that 9b00c3e is part of the problem (though it didn't cause it originally).  Apologies, this is a brain dump as I've not time to research this at the moment (I'm not using addPloneSite.py), but I think the chmod command in buildout.cfg.j2 bails out if theres no permission on(or ownership of) the ${buildout:var-dir}, whereas the original command, or one like this:
`find  ${buildout:var-dir} -maxdepth 1 -exec chmod -R ug+rwX,o-rwx {} \;`
would still try to chmod the contents of the var-dir.

**Comment by djowett** [comment]
My PR above is just a tidy up of error messages, but on looking at this, I don't have any outstanding issue here.  @MrTango do you? If not I suggest we can close this....
